OFFSET_X = 0
OFFSET_Y = 0


BEGIN_ALCHEMY1_X = 1050
BEGIN_ALCHEMY1_Y = 580
BEGIN_ALCHEMY1_DELAY = 1000

BEGIN_ALCHEMY2_X = 690
BEGIN_ALCHEMY2_Y = 530
BEGIN_ALCHEMY2_DELAY = 1000


BEGIN_ALCHEMY1_X += %OFFSET_X%
BEGIN_ALCHEMY1_Y += %OFFSET_Y%
BEGIN_ALCHEMY2_X += %OFFSET_X%
BEGIN_ALCHEMY2_Y += %OFFSET_Y%


Pause
	Loop {
		Click %BEGIN_ALCHEMY1_X%, %BEGIN_ALCHEMY1_Y%, 0
		Sleep 500
		Click %BEGIN_ALCHEMY1_X%, %BEGIN_ALCHEMY1_Y%, 9
		Sleep %BEGIN_ALCHEMY1_DELAY%

		Click %BEGIN_ALCHEMY2_X%, %BEGIN_ALCHEMY2_Y%, 0
		Sleep 500
		Click %BEGIN_ALCHEMY2_X%, %BEGIN_ALCHEMY2_Y%, 9
		Sleep %BEGIN_ALCHEMY2_DELAY%
	}
F6::Pause
